// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2ray.com/core/app/router/config.proto

/*
Package router is a generated protocol buffer package.

It is generated from these files:
	v2ray.com/core/app/router/config.proto

It has these top-level messages:
	Domain
	CIDR
	RoutingRule
	Config
*/
package router

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v2ray_core_common_net "v2ray.com/core/common/net"
import v2ray_core_common_net1 "v2ray.com/core/common/net"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Type of domain value.
type Domain_Type int32

const (
	// The value is used as is.
	Domain_Plain Domain_Type = 0
	// The value is used as a regular expression.
	Domain_Regex Domain_Type = 1
	// The value is a domain.
	Domain_Domain Domain_Type = 2
)

var Domain_Type_name = map[int32]string{
	0: "Plain",
	1: "Regex",
	2: "Domain",
}
var Domain_Type_value = map[string]int32{
	"Plain":  0,
	"Regex":  1,
	"Domain": 2,
}

func (x Domain_Type) String() string {
	return proto.EnumName(Domain_Type_name, int32(x))
}
func (Domain_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Type of RoutingRule value.
type RoutingRule_Type int32

const (
	RoutingRule_Field      RoutingRule_Type = 0
	RoutingRule_ChinaIp    RoutingRule_Type = 1
	RoutingRule_ChinaSites RoutingRule_Type = 2
	RoutingRule_GfwList    RoutingRule_Type = 3
	RoutingRule_GfwIp      RoutingRule_Type = 4
)

var RoutingRule_Type_name = map[int32]string{
	0: "Field",
	1: "ChinaIp",
	2: "ChinaSites",
	3: "GfwList",
	4: "GfwIp",
}
var RoutingRule_Type_value = map[string]int32{
	"Field":      0,
	"ChinaIp":    1,
	"ChinaSites": 2,
	"GfwList":    3,
	"GfwIp":      4,
}

func (x RoutingRule_Type) String() string {
	return proto.EnumName(RoutingRule_Type_name, int32(x))
}
func (RoutingRule_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Config_DomainStrategy int32

const (
	// Use domain as is.
	Config_AsIs Config_DomainStrategy = 0
	// Always resolve IP for domains.
	Config_UseIp Config_DomainStrategy = 1
	// Resolve to IP if the domain doesn't match any rules.
	Config_IpIfNonMatch Config_DomainStrategy = 2
)

var Config_DomainStrategy_name = map[int32]string{
	0: "AsIs",
	1: "UseIp",
	2: "IpIfNonMatch",
}
var Config_DomainStrategy_value = map[string]int32{
	"AsIs":         0,
	"UseIp":        1,
	"IpIfNonMatch": 2,
}

func (x Config_DomainStrategy) String() string {
	return proto.EnumName(Config_DomainStrategy_name, int32(x))
}
func (Config_DomainStrategy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

// Domain for routing decision.
type Domain struct {
	// Domain matching type.
	Type Domain_Type `protobuf:"varint,1,opt,name=type,enum=v2ray.core.app.router.Domain_Type" json:"type,omitempty"`
	// Domain value.
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Domain) Reset()                    { *m = Domain{} }
func (m *Domain) String() string            { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()               {}
func (*Domain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Domain) GetType() Domain_Type {
	if m != nil {
		return m.Type
	}
	return Domain_Plain
}

func (m *Domain) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IP for routing decision, in CIDR form.
type CIDR struct {
	// IP address, should be either 4 or 16 bytes.
	Ip []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Number of leading ones in the network mask.
	Prefix uint32 `protobuf:"varint,2,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *CIDR) Reset()                    { *m = CIDR{} }
func (m *CIDR) String() string            { return proto.CompactTextString(m) }
func (*CIDR) ProtoMessage()               {}
func (*CIDR) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CIDR) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *CIDR) GetPrefix() uint32 {
	if m != nil {
		return m.Prefix
	}
	return 0
}

type RoutingRule struct {
	Tag         string                              `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Domain      []*Domain                           `protobuf:"bytes,2,rep,name=domain" json:"domain,omitempty"`
	Cidr        []*CIDR                             `protobuf:"bytes,3,rep,name=cidr" json:"cidr,omitempty"`
	PortRange   *v2ray_core_common_net.PortRange    `protobuf:"bytes,4,opt,name=port_range,json=portRange" json:"port_range,omitempty"`
	NetworkList *v2ray_core_common_net1.NetworkList `protobuf:"bytes,5,opt,name=network_list,json=networkList" json:"network_list,omitempty"`
	SourceCidr  []*CIDR                             `protobuf:"bytes,6,rep,name=source_cidr,json=sourceCidr" json:"source_cidr,omitempty"`
	UserEmail   []string                            `protobuf:"bytes,7,rep,name=user_email,json=userEmail" json:"user_email,omitempty"`
	InboundTag  []string                            `protobuf:"bytes,8,rep,name=inbound_tag,json=inboundTag" json:"inbound_tag,omitempty"`
	// RoutingRule matching type.
	Type RoutingRule_Type `protobuf:"varint,9,opt,name=type,enum=v2ray.core.app.router.RoutingRule_Type" json:"type,omitempty"`
}

func (m *RoutingRule) Reset()                    { *m = RoutingRule{} }
func (m *RoutingRule) String() string            { return proto.CompactTextString(m) }
func (*RoutingRule) ProtoMessage()               {}
func (*RoutingRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RoutingRule) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *RoutingRule) GetDomain() []*Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *RoutingRule) GetCidr() []*CIDR {
	if m != nil {
		return m.Cidr
	}
	return nil
}

func (m *RoutingRule) GetPortRange() *v2ray_core_common_net.PortRange {
	if m != nil {
		return m.PortRange
	}
	return nil
}

func (m *RoutingRule) GetNetworkList() *v2ray_core_common_net1.NetworkList {
	if m != nil {
		return m.NetworkList
	}
	return nil
}

func (m *RoutingRule) GetSourceCidr() []*CIDR {
	if m != nil {
		return m.SourceCidr
	}
	return nil
}

func (m *RoutingRule) GetUserEmail() []string {
	if m != nil {
		return m.UserEmail
	}
	return nil
}

func (m *RoutingRule) GetInboundTag() []string {
	if m != nil {
		return m.InboundTag
	}
	return nil
}

func (m *RoutingRule) GetType() RoutingRule_Type {
	if m != nil {
		return m.Type
	}
	return RoutingRule_Field
}

type Config struct {
	DomainStrategy Config_DomainStrategy `protobuf:"varint,1,opt,name=domain_strategy,json=domainStrategy,enum=v2ray.core.app.router.Config_DomainStrategy" json:"domain_strategy,omitempty"`
	Rule           []*RoutingRule        `protobuf:"bytes,2,rep,name=rule" json:"rule,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Config) GetDomainStrategy() Config_DomainStrategy {
	if m != nil {
		return m.DomainStrategy
	}
	return Config_AsIs
}

func (m *Config) GetRule() []*RoutingRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func init() {
	proto.RegisterType((*Domain)(nil), "v2ray.core.app.router.Domain")
	proto.RegisterType((*CIDR)(nil), "v2ray.core.app.router.CIDR")
	proto.RegisterType((*RoutingRule)(nil), "v2ray.core.app.router.RoutingRule")
	proto.RegisterType((*Config)(nil), "v2ray.core.app.router.Config")
	proto.RegisterEnum("v2ray.core.app.router.Domain_Type", Domain_Type_name, Domain_Type_value)
	proto.RegisterEnum("v2ray.core.app.router.RoutingRule_Type", RoutingRule_Type_name, RoutingRule_Type_value)
	proto.RegisterEnum("v2ray.core.app.router.Config_DomainStrategy", Config_DomainStrategy_name, Config_DomainStrategy_value)
}

func init() { proto.RegisterFile("v2ray.com/core/app/router/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x97, 0x34, 0xcb, 0x96, 0x93, 0xfd, 0xfa, 0x8b, 0x2c, 0x86, 0xc2, 0xd0, 0x44, 0x15,
	0x21, 0xd6, 0x0b, 0x94, 0x48, 0x45, 0xc0, 0x05, 0x20, 0x34, 0xba, 0x3f, 0xaa, 0x04, 0xd3, 0xe4,
	0x6d, 0x5c, 0x70, 0x53, 0x79, 0xa9, 0x9b, 0x59, 0xa4, 0xb6, 0xe5, 0x38, 0xdb, 0x7a, 0xc7, 0x33,
	0xf0, 0x18, 0x3c, 0x0d, 0x8f, 0x84, 0xec, 0x64, 0x5a, 0x87, 0x56, 0x76, 0xe7, 0x63, 0x7f, 0xbe,
	0xe7, 0x9f, 0xcf, 0x81, 0x17, 0x97, 0x03, 0x45, 0xe6, 0x69, 0x2e, 0x66, 0x59, 0x2e, 0x14, 0xcd,
	0x88, 0x94, 0x99, 0x12, 0xb5, 0xa6, 0x2a, 0xcb, 0x05, 0x9f, 0xb2, 0x22, 0x95, 0x4a, 0x68, 0x81,
	0x36, 0x6f, 0x38, 0x45, 0x53, 0x22, 0x65, 0xda, 0x30, 0x5b, 0xcf, 0xff, 0x92, 0xe7, 0x62, 0x36,
	0x13, 0x3c, 0xe3, 0x54, 0x67, 0x52, 0x28, 0xdd, 0x88, 0xb7, 0x76, 0x96, 0x53, 0x9c, 0xea, 0x2b,
	0xa1, 0xbe, 0x37, 0x60, 0xf2, 0xc3, 0x01, 0x7f, 0x4f, 0xcc, 0x08, 0xe3, 0xe8, 0x0d, 0x78, 0x7a,
	0x2e, 0x69, 0xec, 0xf4, 0x9c, 0x7e, 0x77, 0x90, 0xa4, 0xf7, 0xc6, 0x4f, 0x1b, 0x38, 0x3d, 0x9d,
	0x4b, 0x8a, 0x2d, 0x8f, 0x1e, 0xc1, 0xea, 0x25, 0x29, 0x6b, 0x1a, 0xbb, 0x3d, 0xa7, 0x1f, 0xe0,
	0xc6, 0x48, 0xfa, 0xe0, 0x19, 0x06, 0x05, 0xb0, 0x7a, 0x5c, 0x12, 0xc6, 0xa3, 0x15, 0x73, 0xc4,
	0xb4, 0xa0, 0xd7, 0x91, 0x83, 0xe0, 0x26, 0x6a, 0xe4, 0x26, 0x29, 0x78, 0xc3, 0xd1, 0x1e, 0x46,
	0x5d, 0x70, 0x99, 0xb4, 0xd1, 0x37, 0xb0, 0xcb, 0x24, 0x7a, 0x0c, 0xbe, 0x54, 0x74, 0xca, 0xae,
	0xad, 0xe3, 0xff, 0x70, 0x6b, 0x25, 0x3f, 0x3d, 0x08, 0xb1, 0xa8, 0x35, 0xe3, 0x05, 0xae, 0x4b,
	0x8a, 0x22, 0xe8, 0x68, 0x52, 0x58, 0x61, 0x80, 0xcd, 0x11, 0xbd, 0x06, 0x7f, 0x62, 0xbd, 0xc7,
	0x6e, 0xaf, 0xd3, 0x0f, 0x07, 0xdb, 0xff, 0xac, 0x05, 0xb7, 0x30, 0xca, 0xc0, 0xcb, 0xd9, 0x44,
	0xc5, 0x1d, 0x2b, 0x7a, 0xba, 0x44, 0x64, 0x72, 0xc5, 0x16, 0x44, 0x1f, 0x01, 0x4c, 0xcf, 0xc7,
	0x8a, 0xf0, 0x82, 0xc6, 0x5e, 0xcf, 0xe9, 0x87, 0x83, 0xde, 0xa2, 0xac, 0x69, 0x7b, 0xca, 0xa9,
	0x4e, 0x8f, 0x85, 0xd2, 0xd8, 0x70, 0x38, 0x90, 0x37, 0x47, 0xb4, 0x0f, 0x1b, 0xed, 0x77, 0x8c,
	0x4b, 0x56, 0xe9, 0x78, 0xd5, 0xba, 0x48, 0x96, 0xb8, 0x38, 0x6a, 0xd0, 0xcf, 0xac, 0xd2, 0x38,
	0xe4, 0xb7, 0x06, 0x7a, 0x0f, 0x61, 0x25, 0x6a, 0x95, 0xd3, 0xb1, 0xcd, 0xdf, 0x7f, 0x38, 0x7f,
	0x68, 0xf8, 0xa1, 0xa9, 0x62, 0x1b, 0xa0, 0xae, 0xa8, 0x1a, 0xd3, 0x19, 0x61, 0x65, 0xbc, 0xd6,
	0xeb, 0xf4, 0x03, 0x1c, 0x98, 0x9b, 0x7d, 0x73, 0x81, 0x9e, 0x41, 0xc8, 0xf8, 0xb9, 0xa8, 0xf9,
	0x64, 0x6c, 0xda, 0xbc, 0x6e, 0xdf, 0xa1, 0xbd, 0x3a, 0x25, 0x05, 0x7a, 0xd7, 0xce, 0x4d, 0x60,
	0xe7, 0x66, 0x67, 0x49, 0xd8, 0x85, 0x1f, 0x5b, 0x18, 0x9e, 0xe4, 0xe0, 0x76, 0x4c, 0x0e, 0x18,
	0x2d, 0x27, 0xd1, 0x0a, 0x0a, 0x61, 0x6d, 0x78, 0xc1, 0x38, 0x19, 0xc9, 0xc8, 0x41, 0x5d, 0x00,
	0x6b, 0x9c, 0x30, 0x4d, 0xab, 0xc8, 0x35, 0x8f, 0x87, 0xd3, 0x2b, 0x53, 0x75, 0xd4, 0x31, 0xa2,
	0xc3, 0xe9, 0xd5, 0x48, 0x46, 0x5e, 0xf2, 0xdb, 0x01, 0x7f, 0x68, 0xd7, 0x07, 0x9d, 0xc1, 0xff,
	0xcd, 0x87, 0x8e, 0x2b, 0xad, 0x88, 0xa6, 0xc5, 0xbc, 0x1d, 0xe9, 0x97, 0xcb, 0x3a, 0xd2, 0xac,
	0x5d, 0x33, 0x0d, 0x27, 0xad, 0x06, 0x77, 0x27, 0x77, 0x6c, 0xb3, 0x1e, 0xaa, 0x2e, 0x69, 0x3b,
	0x52, 0xc9, 0xc3, 0x65, 0x62, 0xcb, 0x27, 0x6f, 0xa1, 0x7b, 0xd7, 0x33, 0x5a, 0x07, 0x6f, 0xb7,
	0x1a, 0x55, 0xcd, 0x46, 0x9c, 0x55, 0xd4, 0x16, 0x1a, 0xc1, 0xc6, 0x48, 0x8e, 0xa6, 0x47, 0x82,
	0x7f, 0x21, 0x3a, 0xbf, 0x88, 0xdc, 0x4f, 0x1f, 0xe0, 0x49, 0x2e, 0x66, 0xf7, 0xc7, 0x39, 0x76,
	0xbe, 0xf9, 0xcd, 0xe9, 0x97, 0xbb, 0xf9, 0x75, 0x80, 0xc9, 0x3c, 0x1d, 0x1a, 0x62, 0x57, 0x4a,
	0x9b, 0x02, 0x55, 0xe7, 0xbe, 0x5d, 0xf0, 0x57, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xff, 0xa2,
	0x72, 0xd5, 0x70, 0x04, 0x00, 0x00,
}
